### ISSUE TITLE
API Call Results textbox needs to cleared after successful login

### ISSUE THREAD

**Issue by saraford** [Azure-Samples/active-directory-b2c-dotnet-desktop#10]
steps to reproduce: 

1. Click on sign-in button
2. Close the window
3. Note how the "API Call Results" textbox shows how the user cancelled authentication
4. Click sign-in and successfully sign-in

Results:
The API Call Results textbox still shows the exception from the user cancelled authentication

Expected:
Textbox to be cleared

**Comment by jennyf19** [comment]
@saraford I believe this has been fixed. I'm not able to reproduce this using the steps above for this sample.
