### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by AmeerMansour** [Azure-Samples/active-directory-b2c-dotnet-desktop#102]
![image](https://user-images.githubusercontent.com/47938924/211421121-8bf5af14-2a77-4b6c-a4f9-3e6fbfd4c78e.png)
I tried to use it with my own tenet. it works when i click sign in but if i clicked sign up , it shows me that error
![image](https://user-images.githubusercontent.com/47938924/211421305-cbae9923-c282-48cf-b579-503c15e2a29d.png)

**Comment by bgavrilMS** [comment]
Sorry for the late reply, this is a bug in MSAL, we will be fixing it soon. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4072

**Comment by bgavrilMS** [comment]
PR is out with a fix, but will need to wait for an MSAL release first.
