### ISSUE TITLE
Editing display name and then clicking Call API still shows old name

### ISSUE THREAD

**Issue by saraford** [Azure-Samples/active-directory-b2c-dotnet-desktop#11]
Steps to reproduce:
1. Call API and see the current display name returned
2. Edit profile and change display name
3. Call API 

Results:
previous display name is returned

**Comment by jennyf19** [comment]
B2C takes some time to sync across policies. The api uses the su_si policy, but the edit profile policy was used. each policy is a separate authorization server, so the issue their own tokens. If you wait a bit, the policies will sync on the server side. or, use the token for the last policy used by the user, it will have the most updated claims.
