### ISSUE TITLE
Please add screenshot of azure scope configs

### ISSUE THREAD

**Issue by NikolaosWakem** [Azure-Samples/active-directory-b2c-dotnet-desktop#2]
make sure you don't use custom domains.. only xxx.onmicrosoft.com

**Comment by EvanWeeks** [comment]
Far as I understand it, that's why step 4 is "PENDING"... the UI on Azure isn't set up yet. If @gsacavdm wants to weigh in with more info, that'd be great, since I was trying to get this demo working for a WPF app last night. The presentation at //build/ was exciting, so I'd love to be able to use this stuff. :)

**Comment by gsacavdm** [comment]
The UI is available, we just need to add those steps. Adding @parakhj for visibility.
In short, you need to [register scopes for your web API](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-app-registration#register-a-web-api) and then [grant permissions to your Web API to those scopes](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens#granting-permissions-to-a-web-api)

**Comment by NikolaosWakem** [comment]
I've got a sneaky suspicion that my B2C isn't the same version / config as fabrikamb2c... Or I'm just too dumb to get this working which is just as likely ;-)

**Comment by parakhj** [comment]
Nik, the B2C version should be identical for you. We have a few screenshots of the steps that need to be taken to set up access tokens in [the blog post](https://azure.microsoft.com/en-us/blog/azure-ad-b2c-access-tokens-now-in-public-preview/). Could you describe what you have done so far to get your tenant configured?

**Comment by NikolaosWakem** [comment]
thanks @parakhj  - i have put some screenshots of my config onto https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/issues/4  - i'm sure it's something silly i've configured wrong...

**Comment by NikolaosWakem** [comment]
make sure you don't use custom domains.. only xxx.onmicrosoft.com
