### ISSUE TITLE
Commonality between sign-in and API call scenarios

### ISSUE THREAD

**Issue by ChainReactive** [Azure-Samples/active-directory-b2c-dotnet-desktop#20]
I'm getting started with authenticating my app with MSAL.  Now I'm copying and pasting from this sample.  There's redundancy, however, that I don't want to carry over to my app.

I think that acquiring a token interactively is the same whether it's upon sign-in or in response to an `MsalUiRequiredException` exception thrown during an API call.  In my app, I'd like this to be a common `GetTokenInteractively` method that's called in the two scenarios.  

In this sample, I notice that `.WithPrompt(Prompt.SelectAccount)` is called upon sign-in but not for an API call.

https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop/blob/fc41c987d348aad9288e227591f25caf34333fb6/active-directory-b2c-wpf/MainWindow.xaml.cs#L34

According to `WithPrompt`'s docs, "The default is `Microsoft.Identity.Client.Prompt.SelectAccount`".  So that means all the `.WithPrompt(Prompt.SelectAccount)` lines have no effect and can be safely removed, right?  That would make the code for interactively acquiring tokens more similar between the sign-in and API call scenarios.

One remaining difference between these two scenarios in the sample app, is that the sign-in scenario handles the `AADB2C90118` error to run the Forgot Password user flow.  Could that also apply to the API call scenario?  A user could forget her password while trying to call an API.  Even if not, having that error handling code in the common method wouldn't hurt the API call scenario, right?

**Comment by bgavrilMS** [comment]
About the default prompt - we may change the default, although I would argue this is a breaking change. For example, if you use .WithLoginHint("foo@foo.com") and not provide a prompt, "select_account" might not be the best user experience. 

But as far as it the sample goes, for this version of MSAL, the .WithPrompt config is superfluous.

**Comment by jennyf19** [comment]
closing as answered
