### ISSUE TITLE
Update to MSAL 4

### ISSUE THREAD

**Issue by scharwood** [Azure-Samples/active-directory-b2c-dotnet-desktop#28]
Please update the whole sample to use the new version of MSAL (4).

There are breaking changes from MSAL 3 to 4.

**Comment by TiagoBrenck** [comment]
@scharwood the sample is already using MSAL 4: `<package id="Microsoft.Identity.Client" version="4.0.0" targetFramework="net452" />`. The branch name could be misleading you, but the sample was updated few days ago.

**Comment by scharwood** [comment]
My bad.
I had downloaded just prior to the update.  I viewed the code briefly and didn't notice the changes before I wrote the request.
Thank you.
