### ISSUE TITLE
Following the authentication, AccessToken is null

### ISSUE THREAD

**Issue by Omsaaf** [Azure-Samples/active-directory-b2c-dotnet-desktop#3]
I have tried the sample code with our two types of users:

1. A user saved in Azure B2c
2. A user with a social account from Google

In both cases, I have an AuthenticationResult that looks like this
**AccessToken = null**
ExpiresOn = 0
IdToken = eyJ0eXAiOiJKV1QiLCJhbGciOi......
Scopes={<Valid List of scopes>}
**TenantId=null**
UniqueId=Valid User Id in AzureB2c
User=<User information properly filled by Azure B2C>

The issue is that I am not getting any AccessToken, Hence I can not call my webApi
I have even created a new Application in Azure B2C, and I still get the same exception.

The Experimental library of Microsoft works on our Azure B2C, so I wonder if this is not related to the implementation itself ?

Any help would be appreciated.

**Comment by parakhj** [comment]
Did you give the native app consent to the web api? If you are not sure what that means, check out this [post](https://azure.microsoft.com/en-us/blog/azure-ad-b2c-access-tokens-now-in-public-preview/). For more details, you can check out [this article](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens).

**Comment by AiHaibara** [comment]
I have the similiar problem.
authResult.Account.Username = null
authResult.AccessToken = null
I have the webapi, and call the webapi by aspnet aspnetcore, nodejs all successed, but the desktop wpf failed.
I published scope for webapi read write and add api access in b2c native application in azure portal.
Can you give me some advice?

**Comment by jennyf19** [comment]
@Omsaaf closing. please try w/current sample. issue is not reproducing. thanks.
