### ISSUE TITLE
Sample stuck in an infinite loop showing a blank window with 'redirecting'

### ISSUE THREAD

**Issue by xammob** [Azure-Samples/active-directory-b2c-dotnet-desktop#40]
We noticed this happening yesterday with our main product that uses b2c. I thought I'd try with your sample app and I get the same behaviour on a number of different machines. When I try to login, I just get a blank popup with redirecting inside it. A few things to note

(a) It's impacting our customers not just internal users
(b) It doesn't seem to happen on a clean machine (I created one in an Azure vm)
(c) It doesn't seem to happen with a new user account

The big difference that gets everything working though it to change from login.microsoftonline.com to b2clogin.com

        private static readonly string Tenant = "mytenantname.onmicrosoft.com";
        private static readonly string AzureAdB2CHostname = "mytenantname.b2clogin.com";

**Comment by xammob** [comment]
Similar issue to this one https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1385. Note the solution at the end regarding the registry key deletion which at least offers a solution without passing a new client to the end users

**Comment by jennyf19** [comment]
@xammob Fix is out. Please confirm it is working for you.

**Comment by foxyjess1** [comment]
@jennyf19 ..... @xammob works with me - same company. So I can confirm on his behalf the fix is good for us. Thanks so much for getting this resolved quickly.

**Comment by jennyf19** [comment]
@foxyjess1 thanks for the confirmation. Appreciate your patience as we sorted this out.
