### ISSUE TITLE
Non-HTTPS url redirect is not supported in webview

### ISSUE THREAD

**Issue by kakins** [Azure-Samples/active-directory-b2c-dotnet-desktop#49]
Following the instructions here:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-desktop-app?tabs=app-reg-preview#configure-the-sample

I've assigned my Redirect URI as the tutorial suggests:
![image](https://user-images.githubusercontent.com/14915247/73788846-616ba380-4763-11ea-9792-883c6ebf7964.png)

However, the WPF app returns this:
![image](https://user-images.githubusercontent.com/14915247/73788882-6fb9bf80-4763-11ea-9dc3-1b527fea280d.png)

That said, I'm finding the B2C setup for a desktop application quite complicated and confusing.  I can run the sample app, but I'm having no success using the library with my own B2C tenant.

**Comment by jmprieur** [comment]
This is an enhancement coming to Azure AD B2C.
Not an issue with the sample.

**Comment by kakins** [comment]
I see.  So is the Azure AD B2C documentation just simply inaccurate?  It appears that you can set up this functionality using the github example, but it doesn't appear to work right now.

**Comment by mo3bius** [comment]
I followed all the guide for use my own azure ad b2c tenant. I used the node example and I created the api application on Azure. I also created the native application for windows application on Azure but when I tried to made the login appear an error message: 
<img width="1680" alt="Schermata 2020-02-05 alle 20 19 16" src="https://user-images.githubusercontent.com/11818717/73875208-2ba6e780-4855-11ea-8c9b-38aaa9b592d6.png">

If I tried to add redirect URI appear the same error of @kakins. 

Could something be missing from the guide?

**Comment by tiago-alves** [comment]
I am facing the same issue.

Were you able to fix this?

**Comment by jennyf19** [comment]
@ktsakas do you know the status of this w/B2C? thx.

**Comment by rrperkin** [comment]
Having the same problem. How do I modify _this_ sample so that it works?

**Comment by mmacy** [comment]
@ktsakas @jennyf19 Something must have changed on the service or library side as the doc referenced above previously worked with this sample. My gut feeling is something on the app registration end might have changed.

@kakins When you registered your native client application in the Azure portal, did you use **Applications** or **App registrations (Preview)**?

![image](https://user-images.githubusercontent.com/13394541/83040025-a9088a80-9ff3-11ea-96bd-3716ffde41ce.png)

**Comment by rrperkin** [comment]
@mmacy I'm struggling with the same problems. I used the App Registrations (Preview) and had to use this to get the interactive flow working in this sample: 

```
     PublicClientApp = PublicClientApplicationBuilder.Create(ClientId)
                .WithB2CAuthority(Authority)
                .WithRedirectUri("http://localhost/")
                .Build();
```

**Comment by jennyf19** [comment]
@rrperkin Thanks for the additional info. I'll take a look

**Comment by jennyf19** [comment]
@rrperkin i made the fixes in the main branch. will need need to update the documentation now and Readme. Will do shortly. You will need to use `.WithRedirectUr()` now, due to changes in the portal.
