### ISSUE TITLE
Missing Access Token

### ISSUE THREAD

**Issue by ddobric** [Azure-Samples/active-directory-b2c-dotnet-desktop#5]
When executing AcquireTokenAsync in sample _**active-directory-b2c-dotnet-desktop**_  the AccessToken is missing and IdToken is set.
Not sure if this is correct behavior.
Assuming that IdToken contains JWT, then the sample should use IdToken instead of AccessToken in following line:

`
 ResultText.Text = await GetHttpContentWithToken(App.ApiEndpoint, authResult.AccessToken);
`

Last but not least, for some reason encoded token in IdToken seems not to be correct.
Getting following after decoding:

> {"typ":"JWT","alg":"RS256","kid":"X5eXk4xyojNFum1kl2Ytv8dlNP4-c57dO6QGTVBwaNk"}⦗炣㓓##㳃₦榢#㓓##Ss₧fW"#⣒ア¦緲#⦇GG3Ⲷƶv梦֖7&綶gF榆榒涶ҳsSc㖳&RӦSӆ#&B֓v#b֦S&#V63&r磢ゲ"§7V"#⣦f3F3"֓㶢ӃsVRӃ㆒ӃS&C㶦F3S梢¦VB#⣦3㓓RӖcCbӆSVRӖ#RӖ6C

**Comment by parakhj** [comment]
The weird characters indicate that copying and pasting might have messed up the characters in the idtoken. 

You should be obtaining an access token if you're calling an API. If you didn't get an access token, try following [this document](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens).

**Comment by jennyf19** [comment]
@ddobric closing, but please reopen if you need assistance w/this. thanks.
