### ISSUE TITLE
Is there any plans to upgrade MSAL library to 4.7 version.

### ISSUE THREAD

**Issue by vedeevi** [Azure-Samples/active-directory-b2c-dotnet-desktop#52]
Currently this sample is referencing MSAL 2.7 version, is there any plan for you to upgrade the MSAL library version to latest 4.7 version?

Thanks,
Vedeevi

**Comment by jennyf19** [comment]
Hi @vedeevi not sure what you mean. The project is updated to the latest MSAL.
This is the PR for the next release (not out yet):
![image](https://user-images.githubusercontent.com/19942418/80774856-f2f47280-8b12-11ea-95f1-3f384a6b7bee.png)
You can see it's been consistently updated;
![image](https://user-images.githubusercontent.com/19942418/80774909-0f90aa80-8b13-11ea-8780-6988a910fa32.png)
Where are you seeing it's on 2.7?
cc: @jmprieur

**Comment by jennyf19** [comment]
closing as it is updated, but would like to know where @vedeevi saw it's on 2.7. ty.

**Comment by mmacy** [comment]
@vedeevi @jennyf19 In the past, there were a few articles on docs.microsoft.com that had direct *.zip download links to the **master** branch of the sample. When the default branch of the sample was subsequently updated to be the **msalv3** branch, the docs were missed in the update, and thus no longer linked to the latest version of the sample (the master branch remained on 2.7 while the msalv3 branch, the new default, was the one that was regularly updated).

All of those links _should_ now be fixed, but do please let us know if you arrive on the master branch from a link in docs as there might still be a stray link out there somewhere. Thanks!
