### ISSUE TITLE
AccessToken is null in authResult

### ISSUE THREAD

**Issue by rrperkin** [Azure-Samples/active-directory-b2c-dotnet-desktop#56]
At this point in time, after changing the demo to use my own B2C coordinates, I'm getting logins with the interactive flow, but the bearer token is null. 

APIScopes looks like this (tenant urls are incorrect here (I'm hiding my tenant name) but they work in the demo, all the way through the interactive authentications):         

```
        public static string[] ApiScopes = { $"https://{Tenant}.onmicrosoft.com/api/user_impersonation" };
        public static string ApiEndpoint = "https://graph.microsoft.com/";
        public static string AuthorityBase = $"https://{Tenant}.b2clogin.com/tfp/{Tenant}/";
```

What I'm really trying to do is use graph.microsoft.com/v1.0/Me, which I thought would be simple, given the very, very strong urging by Microsoft to switch to Graph for B2C. Alas, no bearer token, no Graph. (If I can get it working I'll likely push the branch so that there's a decent *simple* interactive desktop demo for B2C Graph)

I'm not entirely sure I've got this understood correctly, but without a bearer token I can't even get a good error message. 

![image](https://user-images.githubusercontent.com/466101/83046742-48318000-9ffc-11ea-851a-0dc88ab0c310.png)

**Comment by jennyf19** [comment]
@rrperkin haven't tried this out. will try to take a look shortly.

**Comment by jennyf19** [comment]
@jmprieur any thoughts on this one?

**Comment by rrperkin** [comment]
It's been about six months @jennyf19, so it might help to look over the open discussion here: [https://github.com/MicrosoftDocs/azure-docs/issues/56756](https://github.com/MicrosoftDocs/azure-docs/issues/56756)

...addressing the way the documentation misled me into believing that there should have been an access token for B2C user impersonation. Since the samples go with the documentation, I urge you all to read through the thread, especially the post that contains the text "That's the demo and tutorial you don't have." 

And, "He (and I) are looking for the architecture meta-document that maps out Microsoft's Authentication/Authorization model. .NET Core. If it's nothing more than a link to those docs, then no, they won't work. If that document were reworked to include the B2C details, it might."

While the discussion was centered around documentation it might inform what you're investigating here. (And, I have no idea why I have to customize so deeply to get B2C flow for "Work or School Accounts", which is really what would help with my mob of customers who are also O365 tenant account holders and would prefer to "federate" without needing to create an app registration in their own AD.)

**Comment by jennyf19** [comment]
@rrperkin apologies for the delayed response.

Thanks for including the other issue, looking it over, @JasSuri is the expert here, and seems he answered and took your feedback.

You cannot call the MS Graph /me endpoint with a user signed in with a B2C authority (b2clogin.com). You can use the MS Graph to do [administrative things](https://docs.microsoft.com/en-us/azure/active-directory-b2c/manage-user-accounts-graph-api) in your B2C tenant, like create or maintain applications, update or manage users (in this case using an AAD authority (login.microsoftonline.com), but with a B2C tenant). This is restricted because the users signed in with a B2C authority are behind social identities, external to Microsoft. 

And, yes, this is an area where we need to improve documentation, as @JasSuri mentioned.

You can request more claims about the sign-in user from the id_token, and even add custom claims. I know this is not the same as calling MS Graph, but you can customize what you would like returned here about the signed-in user with the B2C authority. 

@mmacy please see some of the doc suggestions raised [here](https://github.com/MicrosoftDocs/azure-docs/issues/56756#issuecomment-658387456). Thank you.

cc: @jmprieur

**Comment by rrperkin** [comment]
@jennyf19: "This is restricted because the users signed in with a B2C authority are behind social identities, external to Microsoft."

I accept that it's restricted. It blows my mind, though. I offer this "why" only as context, in case the architecture ever comes under discussion:

- "Email" signups are not behind social identities. The signup flow looks little different than a live.com account creation. 
- I can create live.com accounts using a social identity email address (I actually have two of those). The /me endpoint works with those. 
- You have to perform a circumlocution or two in Azure's panels to create a pure-AAD administrative user. (You have to know that's what is needed)

![image](https://user-images.githubusercontent.com/466101/100029342-edf45a80-2da5-11eb-8285-662fe8d63ed5.png)


"You can request more claims about the sign-in user from the id_token, and even add custom claims. I know this is not the same as calling MS Graph, but you can customize what you would like returned here about the signed-in user with the B2C authority."

Doesn't that round-trip through the user's computer? If there's a claim with info I don't want scraped by the user, it doesn't seem like the right use case.  

Well, what I wanted initially was a simple test that access to MS graph was working properly. In Graph demos generally, the /me endpoint is the first demonstrated and by far the simplest Graph call that returns complex data. 

@JasSuri was indeed clear. What was not clear was, as you've said, the documentation. But that clarity contradicted the messaging push promoting MS Graph and b2clogin.com endpoints instead of anything that came before.  (And, COME ON, Google still isn't on board with b2clogin.com? Is this another calendar wars kind of thing?)

Sorry. Just recalling the frustration. Fundamentally I appreciate this interaction, and don't blame humans for emergent complexities like this.

**Comment by jennyf19** [comment]
We appreciate the feedback @rrperkin, and understand the frustration. We will definitely pass along the feedback.

**Comment by jennyf19** [comment]
closing, as we have documentation to improve, but not related to this repo necessarily.
