### ISSUE TITLE
Adjustments required for WPF on .Net Core 3.1

### ISSUE THREAD

**Issue by mentorfloat** [Azure-Samples/active-directory-b2c-dotnet-desktop#60]
The sample doesn't work for WPF apps targeting .Net Core 3.1, but with some tweaking I managed to authenticate with B2C to call my APIs.

`.WithParentActivityOrWindow()` doesn't exist and simply removing it will cause `AcquireTokenInteractive()` to do nothing when the button is clicked. So I changed redirectUri to `http://localhost`.

```csharp
authResult = await app.AcquireTokenInteractive(App.ApiScopes)
                    //.WithParentActivityOrWindow(new WindowInteropHelper(this).Handle) // .Net Framework only?
                    .ExecuteAsync();
```

Doing the above will allow the WPF app to open the default internet browser to authenticate.

Is the above the only way for .Net Core 3.1 WPF right now? Or is there an equivalent embedded browser method like `.WithParentActivityOrWindow()`?

**Comment by jennyf19** [comment]
@mentorfloat MSAL allows you to bring your own [browser](https://github.com/azuread/microsoft-authentication-library-for-dotnet/wiki/CustomWebUi#use-your-own-browser) and here's some more [info](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/System-Browser-on-.Net-Core#embedded-vs-system-web-ui). Does this help?

**Comment by mentorfloat** [comment]
Thanks. Sounded like System Browser is indeed the recommended method so I won't change it then. 

Strangely the [docs say B2C does not support 'any port'](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/System-Browser-on-.Net-Core#how-to-use-the-system-browser-ie-the-default-browser-of-the-os) option, but it works for me?

```csharp
private static readonly string RedirectUri = "http://localhost";
```

I used the above without specifying any port in `.WithRedirectUri`.

**Comment by jennyf19** [comment]
@mentorfloat looks like B2C has not updated their docs. Will touch base with them on this. Yes localhost works with B2C now.
