### ISSUE TITLE
fresh clone fails build because of mix of packages.config and packagereference

### ISSUE THREAD

**Issue by chris-ray** [Azure-Samples/active-directory-b2c-dotnet-desktop#66]
msalv3 branch, fresh clone this morning, open solution, build. Fails because of missing nuget packages. Determined it is because there is a packagereference in the csproj. (off-topic: there is a version mismatch between the one in packages.config and the package reference).  Delete the PackageReference in csproj, build, and now it fetches all the nuget packages to ..\packages. But it fails to build because one of the nuget packages requires PackageReference (the one I deleted). So I put it back, and now build succeeds because i previously downloaded the nuget packages.

**Comment by mixxit** [comment]
also experiencing this

**Comment by jmprieur** [comment]
@chris-ray @mixxit : this week we'll release a new version of MSAL.NET (and update the sample accordingly) that will fix this.
cc: @bgavrilMS @trwalke @neha-bhargava @jennyf19

**Comment by bgavrilMS** [comment]
Looking at this now.

**Comment by bgavrilMS** [comment]
Fixed by reverting the changes and using MSAL 4.23
MSAL 4.24 cannot be used with packages.config, but we fixed this issue in MSAL 4.25, which we are releasing soon

**Comment by chris-ray** [comment]
Thanks for the quick work! 👍
