### ISSUE TITLE
wrong link in Readme

### ISSUE THREAD

**Issue by nataliahering** [Azure-Samples/active-directory-b2c-dotnet-desktop#73]
In the readme of this repo here https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop#step-4-register-your-native-app the " register your native app in your B2C tenant" redirects to the web app instructions instead, so I think it should be changed to redirect in the native app (https://docs.microsoft.com/en-gb/azure/active-directory-b2c/add-native-application?tabs=app-reg-ga)

**Comment by jmprieur** [comment]
Thanks for the heads-up. @nataliahering 
This is fixed
