### ISSUE TITLE
Additional information in the documentation

### ISSUE THREAD

**Issue by nataliahering** [Azure-Samples/active-directory-b2c-dotnet-desktop#74]
It would be useful to add some documentation on how to configure the URI scheme in the .NET app, which will eventually used in the production scenario as the redirect uri instead of the localhost. For example, how we can configure this ```com.onmicrosoft.contosob2c.exampleapp://oauth/redirect```

**Comment by jmprieur** [comment]
@nataliahering : for  NET desktop, we recommend you use `.WithDefaultRedirectUri()`

**Comment by nataliahering** [comment]
@jmprieur thanks for the answer. This is just using also the localhost. I removed the localhost from the app registration in the b2c portal and only kept the ```msal<...>://auth``` and ```https://<...>.b2clogin.com/oauth2/nativeclient``` and used the ```.WithDefaultRedirectUri()``` in the .net call. I got this error:

```
 Only loopback redirect uri is supported, but https://login.microsoftonline.com/common/oauth2/nativeclient was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. 
``` 

So localhost is the only way, even for production purposes?

**Comment by jmprieur** [comment]
@nataliahering : Yes; if you you using the system browser, http://localhost is fine, even in production. In practice, MSAL.NET chooses a port, and there is a protocol (PKCE) that protects from a man in the middle attack (that is even if someone was able to get the auth code flow, they wouldn't be able to redeem it)

**Comment by nataliahering** [comment]
Thanks @jmprieur for the prompt reply. I am aware of this protocol, so I was not concerned about the security. According to this documentation https://docs.microsoft.com/en-gb/azure/active-directory-b2c/tutorial-desktop-app?tabs=app-reg-ga using localhost is only for development and for production we should define a unique custom scheme. Is the doc outdated ?

**Comment by jmprieur** [comment]
Oh I see. thanks for the heads-up, @nataliahering
Yes, I think it's outdated. When using the system browser there is no other choice. When using the embedded browser you can have something else, but a lot of social identities won't work in the embedded browser, so ... yes.
I'm going to edit the doc

**Comment by jmprieur** [comment]
Actually, @nataliahering : do you mind raising an issue in that documentation: https://docs.microsoft.com/en-gb/azure/active-directory-b2c/tutorial-desktop-app?tabs=app-reg-ga ?
I'm not a owner, and it seems to me that the app registration paragraph does not apply at all for B2C here (only to AAD).

**Comment by nataliahering** [comment]
ok nice, done https://github.com/MicrosoftDocs/azure-docs/issues/74049

I think you can close this issue, thanks for your assistance :)

**Comment by jmprieur** [comment]
Thanks @nataliahering !
