### ISSUE TITLE
`AquireTokenSilent` getting bearer token for the wrong account

### ISSUE THREAD

**Issue by leskodan** [Azure-Samples/active-directory-b2c-dotnet-desktop#82]
If you have authenticated to a wpf app with multiple accounts (during different sessions), it is possible to make a token refresh request that returns a bearer token for the wrong account. 

I assume that this is due to the `accounts.FirstOrDefault()` argument in the token refresh below.

```csharp
        public async Task PostScreeningRecord(string url, ScreeningRecord screeningRecord)
        {
            AuthenticationResult authResult = null;
            var app = App.PublicClientApp;
            var accounts = await app.GetAccountsAsync(App.PolicySignUpSignIn);

            try
            {
                authResult = await app.AcquireTokenSilent(App.ApiScopes, accounts.FirstOrDefault())
                    .ExecuteAsync();
            }
```

Presumably, I need to be passing in an argument that specifies the account to refresh the token for. It was my assumption that the default would be the account that is currently signed in, but this doesn't necessarily appear to be the case. 

Is there documentation, or a recommended implementation for passing a specified account argument?

**Comment by leskodan** [comment]
Checking in again for guidance?

**Comment by jmprieur** [comment]
@leskodan : if you have multiple accounts, you need to provide an account selector to choose the right account
this is beyond the scope of this sample.

**Comment by leskodan** [comment]
Got it, thank you!
