### ISSUE TITLE
Persist authentication

### ISSUE THREAD

**Issue by leskodan** [Azure-Samples/active-directory-b2c-dotnet-desktop#84]
This sample has helped me get a fairly good understanding of how to manage authenticated users and sessions on a local Windows 10 app. One thing that I would like to be able to do however, is persist the authenticated session.

**Current Behavior**
- Login to application
- Acquire id token and access token
- Refresh access token as necessary
- Close app -> authenticated session ends.

**Desired Behavior**
I would like to be able to achieve the behavior above _plus_ be able to open the application again after closing it and still be authenticated.

Right now, authenticated session ends when I close the app. How would I go about chaining this behavior?

**Comment by bgavrilMS** [comment]
This is how to add persistence layer - https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=desktop

This solution works on Win Mac and Linux
