### ISSUE TITLE
Example not working anymore in net 5 WPF app

### ISSUE THREAD

**Issue by vcarlucci** [Azure-Samples/active-directory-b2c-dotnet-desktop#86]
Hello, we are trying to migrated our application which contains the most authentication concept from this example to .net 5 WPF (base app project built on .net framework "4.x").

In our actual app it works fine, when we migrate the app to .net 5, the registration returns always an exception (some informatons with url redirect etc...).

Also the method "WithParentActivityOrWindow" is not available in .net 5 and has to be removed from the code.

Note: #60 (closed issue) has similar issue

We have changed several code but are not able to make it run under .net 5.. We have also used for verification purpose the credential from this demo, but this also fails.

Can you update the demo code for net 5 compatibility ?

**Comment by jmprieur** [comment]
@maliksahil do you want to have a look?

**Comment by vcarlucci** [comment]
Reproduction steps: 
1. I have cloned this project and opened it in VS2019 v16.11.5
2. Add inside the solution a empty net 5 wpf app project
3. Copy files from this demo to the net 5 proj:
    - App.xaml
    - MainWindow.xaml
    - TokenCacheHelper.cs
4. Add nuget:
    - Microsoft.Identity.Client (4.37.0, latest available)
    - Newtonsoft.Json (13.0.1, laatest available)
5. Build & Run net 5 application


Following error occures after Sign In
(the login page is surprisingly showing the first time, and I can enter my credentials, what in our issue is not happening. All following restarts of the application and pressing sign in button, directly the error message will be shown without login page)

![Snag_2f19ed77](https://user-images.githubusercontent.com/33085651/142399993-8c13d191-57f3-4a18-9b68-63f3a0ddc605.png)

Error Text:

Error Acquiring Token:
MSAL.NetCore.4.37.0.0.MsalClientException: 
	ErrorCode: loopback_redirect_uri
Microsoft.Identity.Client.MsalClientException: Only loopback redirect uri is supported, but https://fabrikamb2c.b2clogin.com/oauth2/nativeclient was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details
   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.UpdateRedirectUri(Uri redirectUri)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
   at active_directory_b2c_wpf.MainWindow.SignInButton_Click(Object sender, RoutedEventArgs e) in C:\Users\Operator\Desktop\Authentication Test\active-directory-b2c-dotnet-desktop-msalv3\NET5_Test\MainWindow.xaml.cs:line 36

**Comment by vcarlucci** [comment]
@jmprieur @maliksahil any news regarding this issue? Or can you give a short roadmap when we can expect an investigation? As we use this sample and we have to migrate our existing wpf apps to net 5, we are blocked actually because of this issue.
Thank you for your support.

**Comment by jmprieur** [comment]
@vcarlucci : did you try to add http://localhost as a redirect URI for your application?
The exception says it's required

cc: @bgavrilMS

**Comment by vcarlucci** [comment]
@jmprieur already done with http://localhost and with http://localhost(portNo). Both no improvement

Details:

I tried the localhost as follow in the existing method call, in App.xaml.cs

....
.WithRedirectUri("http://localhost")
...

**Comment by bgavrilMS** [comment]
To use the system browser (default on .net core / net 5), you have to configure http://localhost redirect URI both in the app and in the application registration. 

To use an embedded browser, see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WebView2

Note that you have to target `net5.0-windows10.0.17763.0` instead of `net5.0-windows` (edit your csproj file to change this). 
This does not preclude you from using the app on any version of Windows, all the way down to Win 7, if you add 

`<SupportedOSPlatformVersion>7</SupportedOSPlatformVersion>`

Do however note that the app size is considerable larger.

**Comment by vcarlucci** [comment]
I have changed the csproj configuration as you mentioned to `net5.0-windows10.0.17763.0` what already helped. This in both cases, when I migrate this sample project to net 5 and also our own application registration. Seems no more code change is necessary, also it worked without localhost definition. 

Seems this fixed my issue. 

Just for understanding, is this setting now limitating our application to this windows specified version? When we have to think about this next time, when we would target windows 11? 

Anyway, thank you all for your quick and helpfull support!

**Comment by bgavrilMS** [comment]
MSAL uses 2 embedded browsers on net core / net 5: 

- a new one based on WebView2
- a legacy one based on WebBrowser control

If the first is not available, it should fallback to the second. 

Please make sure to do some testing with your new app. WebView2 is known to be a bit problematic, as it is fairly new tech.

**Comment by bgavrilMS** [comment]
Let us know if you have any more questions or problems, happy to help.

**Comment by vcarlucci** [comment]
Thank you for the insights, so we will make some extra testing here.
